// pages/category/category.js
Page({

  /**
   * 页面的初始数据
   */
  data: {

    leftMenuList:[],

    rightcontent:[],
    //被点击的左侧的菜单
    currentIndex:0

  },

  type:[
    {
      "cat_id":1,
      "cat_name":"现实小说",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"围城",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":"image/01_1.jpg"
        },
        {
          "cat_id":3,
          "cat_name":"房思琪的初恋乐园",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":"image/01_2.jpg"
        },
        {
          "cat_id":3,
          "cat_name":"人生海海",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":"image/01_3.jpg"
        },
        {
          "cat_id":3,
          "cat_name":"丰乳肥臀",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":"image/01_4.jpg"
        },
        {
          "cat_id":3,
          "cat_name":"活着",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":"image/01_5.jpg"
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"悬疑恐怖",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"科幻经典",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"玄幻穿越",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"武侠经典",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"游戏竞技",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"科幻未来",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"悬疑灵异",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"政治军事",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"言情小说",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"漫画杂志",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"金融投资",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"人工智能",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"历史考古",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"家庭育儿",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"中外名著",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    },
    {
      "cat_id":1,
      "cat_name":"外语学习",
      "cat_pid":0,
      "cat_level":0,
      "cat_deleted":false,
      "cat_icon":".jpg",
      "children":[
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        },
        {
          "cat_id":3,
          "cat_name":"书名",
          "cat_pid":1,
          "cat_level":1,
          "cat_deleted":false,
          "cat_icon":""
        }
      ]
    }
  ],

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    this.getCates();
  },

  getCates() {
    let leftMenuList=this.type.map(v=>v.cat_name);
    let rightcontent=this.type[0].children;
    this.setData({
      leftMenuList,
      rightcontent
    })
  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})